### ISSUE TITLE
@onResize Modify parameter value

### ISSUE THREAD

**Issue by QMZhao** [mauricius/vue-draggable-resizable#108]
@resizing="(x, y, w, h) => onResize(w, x, y, h)" >
Can I modify the parameter values in this method， i want in other ways modify the "w", but ican't

**Comment by QMZhao** [comment]
thanks

**Comment by mauricius** [comment]
I don't know if I fully understand your question. Do you want to programmatically change the value of `w`, in order to reflect that change also in the component? In this case you can't. Callback arguments are just copies of the original values. If you want to change the value using component props you can check out version 2 of the component on the dev branch, which implements this functionality as well.

**Comment by QMZhao** [comment]
thank you!
