### ISSUE TITLE
Is there a reason why the elements don't react to changes of their props?

### ISSUE THREAD

**Issue by larsrinn** [mauricius/vue-draggable-resizable#14]
If the props of an vue-draggable-resizable change (e.g. `x`, `h`) change after the initial rendering of the object, the object is not rerendered. Hence, the changes are ignored. Probably this is due to the fact, that these props are only used in the `created` and `mounted` functions? Is there a special reason for that? I would like to be able to control the position of an element reactively based on the state of my app.

**Comment by mauricius** [comment]
I guess it could be possible to watch `x`, `y`, `w` and `h` props and react accordingly. However I need to insert additional checks, in order to ensure that each component doesn't exceed its parent bounds and maybe fallback to a suitable value. Don't really know what is the right approach in this particular case.

Let me experiment a little bit before doing something silly.

**Comment by eyelandlau** [comment]
You can change the 'width' ,'height' ,'top' and 'left' when the props change.
I don't konw how to post a picture here ,however I can post my code:
`watch: {
    y() {
      this.top = value;
    },
    x() {
      this.left = value;
    },
    w(value) {
      this.width = value;
    },
    h() {
      this.height = value;
    }
  }`

**Comment by eyelandlau** [comment]
You can change the 'width' ,'height' ,'top' and 'left' when the props change.
I don't konw how to post a picture here ,however I can post my code:
`watch: { y() { this.top = value; }, x() { this.left = value; }, w(value) { this.width = value; }, h() { this.height = value; } }`

**Comment by eyelandlau** [comment]
You can change the 'width' ,'height' ,'top' and 'left' when the props change.
I don't konw how to post a picture here ,however I can post my code:
`watch: { y(value) { this.top = value; }, x(value) { this.left = value; }, w(value) { this.width = value; }, h(value) { this.height = value; } }`

**Comment by lmr2391** [comment]
Yes, but than you would have to include the checks for not exceeding the parent's bounds, etc. in the watcher-functions. So I absolutely see how this is not trivial.

However, I realized that I don't need the components, whose position and size I want to define with a reactive prop, to be resizable or draggable. So I ended up achieving my desired result by just using a plain simple `div`

**Comment by alxpez** [comment]
Any update on this issue?

**Comment by mauricius** [comment]
> Any update on this issue?

Yeah, I'm working on it. You can grab the latest commit 20a9b1c from the develop branch if you want to test it.

**Comment by alxpez** [comment]
Thanks! Will do

**Comment by alxpez** [comment]
I've done some testing, playing around, dragging/resizing and doing some "time travel" on the vuex store (the vdr props bind with the store's state props)... so far I haven't encountered any problem, I'll let you know if I see anything odd but right now it works swell!

**Comment by alxpez** [comment]
Are you planning on including these changes in the next release? It would be great!

**Comment by benmann** [comment]
Same situation, can confirm that it's working fine so far! 👍

**Comment by Serhiy-Shekhovtsov** [comment]
Hi @mauricius, any plans on including these changes in next release?

**Comment by dkatten** [comment]
Bump!

**Comment by dillingham** [comment]
Bump, the x,y,w,h map to inputs for me.. 
Being able to adjust the inputs manually allows for more precision. 
Also, using arrow keys to move x,y gives it more image editor like qualities.

`:w="object.layers[index].width"
`:h="object.layers[index].height"
`:x="object.layers[index].x"
`:y="object.layers[index].y"

**Comment by mauricius** [comment]
Sorry everyone for such a long wait, but you know how this works. I can focus on this project only in my spare time, which is limited. I'm also moving from my current job and my current place so this means even less time to dedicate to open source (unfortunately).

On this issue however I have a couple of words to spend. In my opinion, introducing the concept of controlled component (in which you provide the state) and uncontrolled component (in which the state is kept inside the component) would require a breaking change because I really think that watchable props and one-time props should be separated. 

So my thoughts are basically to leave `w`, `h`, `x` and `y` for controlled components, where you provide you own values, but you are required to listen to callbacks in order to adjust your values if they are not valid (outside parent for example). For uncontrolled components I could introduce new props `defaultPosition` and `defaultSize` for example to make it work like now.

Matt Zabriskie explains this problem better than me on his project https://github.com/mzabriskie/react-draggable#controlled-vs-uncontrolled, so it's definetly worth a read.

I would like to know your thoughts about this, even if I don't have the time to work on it right now.

**Comment by dillingham** [comment]
Maybe it would be simpler to pass an `id` to the component, have a listener within the mounting of the component, and fire an event for that `id` with new w,h,x,y parameters?

**Comment by mauricius** [comment]
Awesome work @kirillmurashov I will definitely check it out!

**Comment by romucci** [comment]
So... what's the solution then? 🗡

**Comment by mauricius** [comment]
Dev branch has the new major version which introduces this behavior, as well as other improvements and bug fixes. Right now it is in beta and needs a few more tests, but I'm planning to release it soon. I would like to thank @kirillmurashov work, from which I took some bits of inspiration.

Sorry for the wait, better late than never 😄

**Comment by dillingham** [comment]
@mauricius thanks! I needed this so bad. Any ETA on release?

**Comment by mauricius** [comment]
@dillingham Hopefully in a couple of weeks. I'm hoping to have some feedback first, because right now I'm not using the library in any real world project.

**Comment by liquidvisual** [comment]
Hi @mauricius, sorry to resurrect an old thread. I understand this feature is still on the dev branch of v2? I can't find much information on it, outside of some discussion on previous closed issues. 

Will this feature make it into the full version (after current RC)?

**Comment by TitanFighter** [comment]
This already works in RC1

**Comment by liquidvisual** [comment]
Hi all, and @mauricius. I can't seem to get x and y props to work reactively in RC2, am I doing this right? I've set up a Codepen:

https://codesandbox.io/embed/vue-template-l3yx5

**Comment by TitanFighter** [comment]
#144

**Comment by quannetwork** [comment]
This problem also happens to me. Is there any way to workaround?
