### ISSUE TITLE
Assigned Parent too influenced by child location

### ISSUE THREAD

**Issue by alphatrust-dev** [mauricius/vue-draggable-resizable#150]
I have a two divs inside a parent div and the inner divs are centered at differing widths.  When this is done, the parent restraint is affected by the inner divs' locations.

Here's an example:
https://codesandbox.io/s/kxvqv3w1ov

![image](https://thumbs.gfycat.com/ShadyHospitableBichonfrise-size_restricted.gif )

I should be able to move the fields over the red background (which is the parent restraint area) but I can't because I can't go left or top of the fields' container div.

**Comment by mauricius** [comment]
This is definitely my fault because I only tested that feature using parent elements with the same origin point as the component. In your case the provided parent (the red area) has a negative offset compared to the component's direct parent node.

Unfortunately at this point supporting this use case would require substantial changes to the core of the component, which I'm not able to provide at this point in time. Therefore I'm going to remove the parent selector from the next RC of the component. Hopfully I can bring it back on a next major version.

**Comment by alphatrust-dev** [comment]
Here is my work-around solution for posterity's sake: https://codesandbox.io/s/vm9wj16z83
