### ISSUE TITLE
Drag multiple elements

### ISSUE THREAD

**Issue by justLbee** [mauricius/vue-draggable-resizable#176]
Hello. 

Is it possible to select multiple elemts with Ctrl or another button and drag all of them?

**Comment by Everytimeyumi** [comment]
没用人回答吗  我也想用

**Comment by mauricius** [comment]
Since this particular necessity pops up quite regularly and I'm definitely not planning to add it to the component, I decided to create a small example inside storybook to showcase how you can implement it directly in your application, by combining props and events. It's far from perfect, but it can serve as a good starting point.

https://mauricius.github.io/vue-draggable-resizable/?selectedKind=How%20To&selectedStory=Drag%20Multiple%20Elements&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel
