### ISSUE TITLE
Snap to other components 

### ISSUE THREAD

**Issue by Cross77** [mauricius/vue-draggable-resizable#18]
Is any way to snap components to other draggable components or some div ( to parent ) ? Like jQueryUI
https://jqueryui.com/draggable/#snap-to

**Comment by mauricius** [comment]
No and it's something that I'm not willing to implemement because, in my opinion, it is a functionality that traspass the boundaries of a web component. As a rule of thumb, components should be as much as dumb as possible, meaning that they shouldn't be aware of what's around them.

That said, it would be totally possible to build this functionality from the perspective of the App itself, as it knows the coordinates and the size of each VDR component in its scope. However, for making it work I should first implement the reactivity of props, as referenced in this issue #18
