### ISSUE TITLE
How do you get the length and width of one of the multiple elements?I found no such example

### ISSUE THREAD

**Issue by PiccoloYu** [mauricius/vue-draggable-resizable#180]

**Comment by SnowNooDLe** [comment]
Hope you have solved otherwise this is what I have achieved and hope this can help you.

If you have one canvas and multiple resizable elements inside, then follow the reference link I provided, my approach is for two different resizable elements in two different containers.

`<div class="imagecontainer">
            <div class="leftstage">
              <VueDraggableResizable
                :x="elements[0].x"
                :y="elements[0].y"
                :w="elements[0].width"
                :h="elements[0].height"
                :parent="true"
                :debug="false"
                :min-width="100"
                :min-height="100"
                @resizestop="(left, top, width, height) => onResizstop(elements[0].id, left, top, width, height)"
              />
            </div>
            <div class="rightstage">
              <VueDraggableResizable
                :x="elements[1].x"
                :y="elements[1].y"
                :w="elements[1].width"
                :h="elements[1].height"
                :parent="true"
                :debug="false"
                :min-width="150"
                :min-height="150"
                @resizestop="(left, top, width, height) => onResizstop(elements[1].id, left, top, width, height)"
              />
            </div>
          </div>`

data as following, (you can choose id name whatever you want as long as you can distinguish)
`elements = [
    {
      id: "one",
      x: 100,
      y: 100,
      width: 300,
      height: 300
    },
    {
      id: "two",
      x: 100,
      y: 100,
      width: 300,
      height: 300
    }
  ];`
I only have an event when resizestop as my project is dealing with compare coordinate, so I do not need while dragging or resizing.
After resizestop, now I can compare coordinates by using x,y, x+width, y+height to see whether all two resizable rectangles are sitting on expected coordinates but currently only printing values.
`onResizstop(
    id: string,
    left: number,
    top: number,
    width: number,
    height: number
  ) {
    console.log("Resize is stopped!");
    console.log(id, left, top, width, height);
  }`

and probably from here, you might also add attributes inside elements such as length & height, so every time you call a certain method, you can update its' id's x, y, width and height value.

Hope this helps!


[reference](https://github.com/mauricius/vue-draggable-resizable/issues/16)
