### ISSUE TITLE
How to use in typescript

### ISSUE THREAD

**Issue by AndersBKnudsen** [mauricius/vue-draggable-resizable#197]
First time I used this library, I did it in JS. 

How to I import and use it in typescript?

**Comment by toytonic** [comment]
There is no definition file included in the project or on definitely typed. You have to write your own or go with the `require` syntax: https://github.com/mauricius/vue-draggable-resizable/issues/151

**Comment by yilingsj** [comment]
参考：[#151#issuecomment-568974075](https://github.com/mauricius/vue-draggable-resizable/issues/151#issuecomment-568974075)

**Comment by SnowNooDLe** [comment]
Hope you have solved by now, otherwise just like 'yilingsj' said,

`declare module 'vue-draggable-resizable'`
put this inside shims-vue.d.ts

`import VueDraggableResizable from "vue-draggable-resizable";`
(css is optional)
`import "vue-draggable-resizable/dist/VueDraggableResizable.css";`

inside <script lang="ts"></script>
For instance,
```
<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import VueDraggableResizable from "vue-draggable-resizable";
import "vue-draggable-resizable/dist/VueDraggableResizable.css";
```
Then add inside @Components

```
@Component({
  components: {
    VueDraggableResizable
  }
})
```

Hope this helps!

**Comment by mauricius** [comment]
Thanks @SnowNooDLe

**Comment by AndersBKnudsen** [comment]
Thansk! :)
