### ISSUE TITLE
input inside vue-draggable-resizable component

### ISSUE THREAD

**Issue by Esvalirion** [mauricius/vue-draggable-resizable#21]
In version 1.2.4, i was could insert input inside the vue-draggable-resizable component, and still have a focus on the input, and the ability to move it. Since version 1.2.5 I can't do this anymore. I'm quite satisfied with version 1.2.4, but there is console.log in the watcher of position.

**Comment by mauricius** [comment]
Yeah I tried to fix a [particular case](https://github.com/mauricius/vue-draggable-resizable/issues/15#issuecomment-319494352), but I realize that it was a bad decision, because the component could no longer be activated from input or textarea elements, as you noticed.

https://github.com/mauricius/vue-draggable-resizable/commit/8def7bfe72b0dd7a63a1d44b48b5f4a975aa66c0 should fix it (v. 1.2.7). I think that this is the best tradeoff between text selection and mouse dragging.

Let me know if it works for you.

![screencast](https://user-images.githubusercontent.com/7000852/29133750-c44cd506-7d34-11e7-8280-cf8a36a3f6f7.gif)

**Comment by Esvalirion** [comment]
Works great!
