### ISSUE TITLE
Would you consider letting :parent support parentElement or window?

### ISSUE THREAD

**Issue by yansenlei** [mauricius/vue-draggable-resizable#22]

**Comment by mauricius** [comment]
Can you please elaborate? I'm not sure to understand what do you mean.

**Comment by b8ne** [comment]
I think he means to support a supplied parent, rather than the nodes direct parent.
ie. `:parentEl="#container"`
Then in the component, if `parentEl` is set, rather than using `this.$el.parentNode.clientWidth` you could use `document.querySelector(this.parentEl).clientWidth` - or similar.
Im assuming provisions for negative coordinates would need to be added in the case that elements are dragged outside of their direct parent.

**Comment by yansenlei** [comment]
![image](https://user-images.githubusercontent.com/23315895/34704033-45375564-f531-11e7-8eec-73fee66e7b58.png)
I want to control dragging through subelements, and it can't be done. Is there a good way to do it?

**Comment by liquidvisual** [comment]
This would be a great addition

**Comment by rubiii** [comment]
I would need to use a sibling element as the "parent" and would love to be able to set a `:parentEl`. Looks like it should be easily possible to add this with just some changes.

**Comment by mauricius** [comment]
With the new major version, available on the dev branch (still in beta), it is possible to pass a custom selector to the `parent` so you can use a different element as parent, instead of the direct node. Check it out if it works for you and let me know.

**Comment by angeliquejw** [comment]
I see this is still only on the `develop` branch; any chance of this making it into the final version? I'm attempting to use this component, but would love to be able to prevent it from being dragged out of the browser, like so:
![Screen Shot 2020-05-04 at 3 31 24 PM](https://user-images.githubusercontent.com/2653980/81005759-70bec380-8e1c-11ea-8596-26f47a74b6f5.png)
and using the default `:parent="true"` is too limiting for my example :(
