### ISSUE TITLE
Bug: Grid snapping issue

### ISSUE THREAD

**Issue by shazow** [mauricius/vue-draggable-resizable#34]
On a grid-enabled canvas, when a box is placed with a 1-unit buffer from the edge, resizing the opposite side will sometimes glitch the side near the edge.

There's a gif in this issue: https://github.com/thousandetherhomepage/ketherhomepage/issues/4#issuecomment-333950549

I also managed to reproduce it in https://mauricius.github.io/vue-draggable-resizable/ but couldn't get it reliably or on the same corner. I got it working on the bottom right corner, same idea.

Not quite sure what the underlying issue is.

**Comment by shazow** [comment]
Actually it might be something on my end, the glitchy behaviour I reproduced is subtly different (I think more to do with the size of the grid that I wasn't accounting for). Will re-open if I can get more info.

**Comment by shazow** [comment]
Okay, I think the issue is indirectly with [reviewDimensions](https://github.com/mauricius/vue-draggable-resizable/blob/bc85ba5180d6c6e4eb5d6e71a0b3e6f50af1dbe4/src/components/vue-draggable-resizable.vue#L159):

I was supplying :x="..." and :y="..." values which change later, but I was expecting them to only be used when the component is initialized.

Would it make more sense to change reviewDimensions to check {this.left, this.top, this.width, this.height} instead of {this.x, this.y, this.w, this.h}?

I believe it would be equivalent, and the state would remain more internally consistent. What do you think?

**Comment by shazow** [comment]
In fact, it seems this.{x,y,etc} are never updated after initialization, so perhaps that check is incorrect as it is now?

**Comment by mauricius** [comment]
Actually I've also noticed a glitch when using the `grid` prop, limited to top and left edges, but I don't know if this is your issue. I just looked into it and is related to the round operation on height and width respectively. 

I'm more and more convinced to use another approach on the future development of the component, maybe using https://github.com/storybooks/storybook, because testing all of these edge cases is really difficult using standard unit tests. Unfortunately these weeks I'm pretty busy at work, so I will not be able to look into it very soon.
