### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by cycold** [mauricius/vue-draggable-resizable#38]
Reloading page using shortcut key ('command + r') when the cursor over the draggable element(don't move cursor) then move the  draggable element you can see bellow gif:

![qweqw](https://user-images.githubusercontent.com/2446601/31801089-437b9732-b50b-11e7-8572-2e4cda687cf2.gif)

> sorry, poor English

> That seems handle the first move on the draggable element the `diffX/Y` equals the fisrt `page.x`

**Comment by mauricius** [comment]
Wow, nice catch! Don't really know what it's happening there, I'll look into it. Thanks for reporting.

**Comment by Serhiy-Shekhovtsov** [comment]
@mauricius I believe the reason is `this.lastMouseX` and `this.lastMouseY` updated on move, but not on mousedown. So if the pointer is already on the draggable element user can press the button and the moving will start but the `this.lastMouseX` and `this.lastMouseY` are both `0` after creating. So when calculating the difference - it will be huge.

**Comment by Serhiy-Shekhovtsov** [comment]
Reproduced and fixed locally. Created a pull request.

**Comment by mauricius** [comment]
Fixed with 93e4633
