### ISSUE TITLE
Is it possible to fix the resizing logic ?

### ISSUE THREAD

**Issue by minedun6** [mauricius/vue-draggable-resizable#58]
@mauricius Currently, looking at the code when resizing using the grid, the component's width will be changed by doing a 
```
grid.width * deltaW / grid.height * deltaH
``` 
the problem with this approach is that it changes the inital width with is an unwanted behaviour.
Shouldn't it just add to the inital width/height like so 
```
this.width + (grid.width * deltaW) /this.width + grid.height * deltaH
```
You can please refer to jquery-ui resizable for any more clarification.

This is a screenshot of the problem that I came across
[Dynamic Tile Builder](https://ibb.co/nPQo7R)
The tile in the screenshot needs to be contained inside the grid cells but the problem is that the tile width gets changed even without resizing.

**Comment by mauricius** [comment]
Ok after a bit of confusion maybe I got what you are saying. Basically the component builds the grid starting from the origin 0,0. So if you define a 160x160 component and a grid of 50x50 pixels, when you touch the resize handles it shrinks immediately to 150x150. And later, if you try to enlarge it, it goes to 200x200 and so on, instead of 210x210.

jQuery UI gets it right.

I'll look into it. Thanks.

**Comment by minedun6** [comment]
Thank you as well for the quick rely 👍 
You just summed it up.

**Comment by mauricius** [comment]
@minedun6 Finally I managed to get this working. You can check the new major version available on the dev branch. Hopefully soon it would replace version 1. Let me know if it works for you.
