### ISSUE TITLE
how do i use it outside of a build system

### ISSUE THREAD

**Issue by nareshv** [mauricius/vue-draggable-resizable#59]
Currently i am having an app outside of the .vue component mechanism. Is there a way where i can use this component in such cases.

I have added `<script src="//unpkg.com/vue-resource"></script>` and then `Vue.component('vue-draggable-resizable', VueDraggableResizable)` to try it out. But doesn't seem to work.

any pointers ?

**Comment by mauricius** [comment]
Fixed with https://github.com/mauricius/vue-draggable-resizable/commit/7e8c3a0fa44b8163cd58fcfa3785a2dad4214585

You can use the compiled version of 1.6.1 on [unpkg](https://unpkg.com/vue-draggable-resizable@1.6.1/dist/index.js). Just include Vue and the component.

```html
<div id="app" style="height: 500px; width: 500px; border: 1px solid red; position: relative;">
  <vue-draggable-resizable :w="100" :h="100" :parent="true">
    <p>Hello!</p>
  </vue-draggable-resizable>
</div>

<script src="https://unpkg.com/vue@2.5.13/dist/vue.js"></script>
<script src="https://unpkg.com/vue-draggable-resizable@1.6.1/dist/index.js"></script>
<script>
  Vue.component('vue-draggable-resizable', VueDraggableResizable.default);

  new Vue({
    el: '#app'
  });
</script>
```

[vue-resource](https://github.com/pagekit/vue-resource) is an HTTP client, don't use it to include external components.
