### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by justanotherco** [mauricius/vue-draggable-resizable#73]
Great component! Just a few suggestions that I think would help general users of the component:

1- Why have you set the validators to be `val > 0` on w, h, minw and minh? There are lots of cases where 0 is the needed value. I removed the validators in the component for my own build, but wouldn't it make more sense to just check for `typeof val === 'number'`?

2- Is there any change you can change the scoped style to be in an (optional) separate css file? Because I'm ending up having to add lots of extra css to my app to overwrite lots of the scoped css to be able to make the component match my apps style.

Thanks!

**Comment by mauricius** [comment]
Thank you!

- You are right, 0 is an acceptable value. I'm going to fix it in the next version of the component.
- Yes I agree, the current approach is not too great. However I don't want to use an external file, but I'm oriented to a modern CSS-to-JS approach, so that you can provide your own styles to the component. I will look into it.

**Comment by gianko** [comment]
Can you use `module` instead of `scope`? had to changed it to use it in a web component.

would gladly sent a PR

**Comment by mauricius** [comment]
@gianko the new major version on the dev branch is style agnostic, so you can provide your own classes and styles. Take a look if this works for you and let me know.
