### ISSUE TITLE
Help for nested components

### ISSUE THREAD

**Issue by tiapossoftware** [mauricius/vue-draggable-resizable#81]
Hi,
If you nest 2 instances of the component it all works fine except for the fact that if the outer component is selected, it remains active when the inner in selected, so the outer one still has drag handles.  Is there a way to prevent this or can I catch the inner select and somehow deselect the outer one in code?

Many thanks.

**Comment by mauricius** [comment]
The required condition to disable a component is that the click event should happen outside it. Therefore clicking an internal component doesn't disable the outer one.

If you don't mind a little bit of verbosity, you can solve this problem using the `active` prop in the following way:

```
<VueDraggableResizable :active="outer_active" @activated="outerActivated">
    <p>Outer Component</p>
    <VueDraggableResizable @activated="innerActivated">
        <p>Inner Component</p>
    </VueDraggableResizable>
</VueDraggableResizable>

<script>
export default {
  data () {
    return {
      outer_active: false
    }
  },
  methods: {
    outerActivated () {
      this.outer_active = true
    },
    innerActivated () {
      this.outer_active = false
    }
  }
}
</script>
```

**Comment by TitanFighter** [comment]
Hi @mauricius 
I tried your version and different my own versions. It seems `vue-draggable-resizable` needs small modification.

Here is the [demo](https://codesandbox.io/s/qp7lrl0nj) of your code.
Try the next:
1. Activate outer (this is the 1st click) and drag it (the 2nd click);
2. Drag inner.
Result: when we drag the inner, at the top we see that `outer_active` is `false`. It looks like `vue-draggable-resizable` still uses `outer_active: true`, because outer also is changing its position.
3. If we release mouse button and drag inner again - everything works as expected (the component sees a new value of `outher_active`.

It seems that on `activated` event `vue-draggable-resizable` does not re-evaluate props value, so, probably as one of the solutions, it is necessary to add `this.nextTick(function () {})` somewhere inside `activated` event in order to let the component to re-evaluate props values. Possibly the same thing happens in case of `deactivated` event.

P.S. In the demo above I changed `:active="outer_active"` to `:draggable="outer_active"`, because it seems that `active` does not work at all (if `active` is responsible for Enabling/Disabling the component).

Here is the [demo](https://codesandbox.io/s/jnl91p34oy) which shows that `active` does not Enable/Disable the component. The state of an `activated`, whether it true or false, does not matter -> anyway you can drag/resize a parent.
