### ISSUE TITLE
Move if transform scale

### ISSUE THREAD

**Issue by andrei2424** [mauricius/vue-draggable-resizable#91]
If parent div scale: `<div style="transform: scale(0.5)"><VueDraggableResizable/></div>` mouse moves faster than div. To fix, add the scale parameter from VueDraggableResizable and change vue-draggable-resizable.vue 401,402 line:

`this.elmX += diffX / this.scale
 this.elmY += diffY / this.scale`

**Comment by aszx-fyh** [comment]
I also had this problem.Need I  copy source and fix it?

**Comment by andrei2424** [comment]
Yes. I made a fork and fixed it myself, but I did not do push

**Comment by aszx-fyh** [comment]
@mauricius  Thanks. About Issue #79,Have you thought about it?

**Comment by mauricius** [comment]
Yep! CSS transforms are just a visible effect, but the underlying component behaves just as normal, because it is not aware that it is transformed. That's why resizing a rotated component feels so unnatural. With scale is easier because you just need to have the scaling factor as prop. With rotation I'm afraid that is entirely a different story, especially for costraining the component within its parent, because the coordinates of its edges are different than the ones calculated by the component.

TBH I don't think I'm ever going to find a solution for this, it is really an edge case.

**Comment by aszx-fyh** [comment]
However,thank very much.

**Comment by tpraxl** [comment]
> You can also check this component https://github.com/kirillmurashov/vue-drag-resize which is similar and offers props for dealing with scale.

# For anyone thinking about using the other component

Problem is, https://github.com/kirillmurashov/vue-drag-resize seems to be abandoned. I'm currently jumping back and forth between both: vue-draggable-resizable and vue-drag-resize. 

I'm very interested in your beta version, but neither does it support parentScale nor is it released on npmjs.com. This is a problem, because I'm relying on parentScale for image elements that can be composed on a responsive canvas. It's important to keep their relative positioning and dimensions.

This is where the other component shines. However, there are at least three show stoppers with https://github.com/kirillmurashov/vue-drag-resize

* It seems to be abandoned
* https://github.com/kirillmurashov/vue-drag-resize/pull/40
* It eats up click events on mobile devices and Chrome Touch Mode. You cannot add a "delete" button inside the draggable element, not even if it is displayed outside the element.

**Comment by tpraxl** [comment]
@mauricius I would love to use your component. But I really need the parent scale as it works in vue-drag-resize.

I would try to add the feature using one additional and optional prop 'parentScale'.

But first I want to make sure that there's a chance for it to be merged. Would you generally accept such a PR?

**Comment by eyaylagul** [comment]
https://github.com/mauricius/vue-draggable-resizable/issues/133#issuecomment-446176024

@tpraxl can you share your solution?

**Comment by tpraxl** [comment]
@eyaylagul I'm actually doing other stuff. I apply a transform: scale.

* Apply a fix width / height to the parent element (I need to keep aspect ratio of the "canvas")
* Watch the grand parent element with a ResizeObserver  https://itnext.io/making-adaptive-vue-components-with-resizeobserver-123b5ebb20ae
* scale the parent element (divide grand-parent-width by fix width) (``:style="`transform: scale(${this.scaleFactor});`)``

**Comment by mauricius** [comment]
See https://github.com/mauricius/vue-draggable-resizable#scale. I forgot to add it do the documentation when I implemented it :sweat_smile:
